name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - 'landingpage/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./landingpage/
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
